from app.services.wellbeing_service import BASELINE_NEAR_TOLERANCE

INSIGHT_LOOKBACK_DAYS = 60
INSIGHT_RECENCY_DAYS = 14
RECENT_WINDOW_DAYS = 7
TREND_WINDOW_DAYS = 28

MATERIAL_SD_FRACTION = 0.5
MATERIAL_RANGE_FRACTION = 0.05
MIN_VALUES_FOR_SD = 8

RECENT_CHANGE_MIN_PER_WINDOW = 3
TREND_MIN_PER_HALF = 5

ASSOC_MIN_PAIRED_DAYS = 14
ASSOC_MIN_GROUP_DAYS = 5
ASSOC_MIN_COMPLETION_GAP = 0.15
ASSOC_MIN_ABS_RHO = 0.30

NLP_MIN_PER_HALF = 4

CONSISTENCY_WINDOW_DAYS = 28
CONSISTENCY_MIN_DAYS = 14
CONSISTENT_SD_MAX = 0.20
VARIED_SD_MIN = 0.35

INSIGHT_MAX_DISPLAY = 4
INSIGHT_NEW_WINDOW_HOURS = 48

CATEGORY_WEIGHTS = {
    "baseline_comparison": 5,
    "recent_change": 5,
    "habit_association": 4,
    "trend": 3,
    "nlp_signal_trend": 3,
    "consistency": 2,
}

VALID_SCORE_MIN = 1
VALID_SCORE_MAX = 100

__all__ = [
    "BASELINE_NEAR_TOLERANCE",
    "INSIGHT_LOOKBACK_DAYS",
    "INSIGHT_RECENCY_DAYS",
    "RECENT_WINDOW_DAYS",
    "TREND_WINDOW_DAYS",
    "MATERIAL_SD_FRACTION",
    "MATERIAL_RANGE_FRACTION",
    "MIN_VALUES_FOR_SD",
    "RECENT_CHANGE_MIN_PER_WINDOW",
    "TREND_MIN_PER_HALF",
    "ASSOC_MIN_PAIRED_DAYS",
    "ASSOC_MIN_GROUP_DAYS",
    "ASSOC_MIN_COMPLETION_GAP",
    "ASSOC_MIN_ABS_RHO",
    "NLP_MIN_PER_HALF",
    "CONSISTENCY_WINDOW_DAYS",
    "CONSISTENCY_MIN_DAYS",
    "CONSISTENT_SD_MAX",
    "VARIED_SD_MIN",
    "INSIGHT_MAX_DISPLAY",
    "INSIGHT_NEW_WINDOW_HOURS",
    "CATEGORY_WEIGHTS",
    "VALID_SCORE_MIN",
    "VALID_SCORE_MAX",
]
