"""create phase 4 database tables

Revision ID: 37392b528fa6
Revises: 
Create Date: 2026-10-03 02:36:38.064544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37392b528fa6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('habits',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('target_value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('target_unit', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('insights',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('insight_date', sa.Date(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_insights_insight_date', 'insights', ['insight_date'], unique=False)
    op.create_index('ix_insights_user_id', 'insights', ['user_id'], unique=False)
    op.create_table('journals',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_journals_user_id', 'journals', ['user_id'], unique=False)
    op.create_index('ix_journals_user_id_entry_date', 'journals', ['user_id', 'entry_date'], unique=False)
    op.create_table('wellbeing_scores',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('score_date', sa.Date(), nullable=False),
    sa.Column('score', sa.SmallInteger(), nullable=False),
    sa.Column('baseline_value', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('score >= 1 AND score <= 100', name='ck_wellbeing_scores_score_range'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_wellbeing_scores_score_date', 'wellbeing_scores', ['score_date'], unique=False)
    op.create_index('ix_wellbeing_scores_user_id', 'wellbeing_scores', ['user_id'], unique=False)
    op.create_table('habit_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('habit_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('log_date', sa.Date(), nullable=False),
    sa.Column('completed_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('is_completed', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['habit_id'], ['habits.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('habit_id', 'log_date', name='uq_habit_logs_habit_date')
    )
    op.create_index('ix_habit_logs_habit_id', 'habit_logs', ['habit_id'], unique=False)
    op.create_index('ix_habit_logs_log_date', 'habit_logs', ['log_date'], unique=False)
    op.create_index('ix_habit_logs_user_id', 'habit_logs', ['user_id'], unique=False)
    op.create_table('journal_analysis',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('journal_id', sa.BigInteger(), nullable=False),
    sa.Column('sentiment_score', sa.Float(), nullable=False),
    sa.Column('stress_indicator', sa.Float(), nullable=False),
    sa.Column('positive_emotion_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['journal_id'], ['journals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('journal_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('journal_analysis')
    op.drop_index('ix_habit_logs_user_id', table_name='habit_logs')
    op.drop_index('ix_habit_logs_log_date', table_name='habit_logs')
    op.drop_index('ix_habit_logs_habit_id', table_name='habit_logs')
    op.drop_table('habit_logs')
    op.drop_index('ix_wellbeing_scores_user_id', table_name='wellbeing_scores')
    op.drop_index('ix_wellbeing_scores_score_date', table_name='wellbeing_scores')
    op.drop_table('wellbeing_scores')
    op.drop_index('ix_journals_user_id_entry_date', table_name='journals')
    op.drop_index('ix_journals_user_id', table_name='journals')
    op.drop_table('journals')
    op.drop_index('ix_insights_user_id', table_name='insights')
    op.drop_index('ix_insights_insight_date', table_name='insights')
    op.drop_table('insights')
    op.drop_table('habits')
    op.drop_table('users')
    # ### end Alembic commands ###
