"""add wellbeing score user date constraint

Revision ID: 581c4cf62edd
Revises: 37392b528fa6
Create Date: 2026-10-03 21:55:18.485093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '581c4cf62edd'
down_revision: Union[str, Sequence[str], None] = '37392b528fa6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_wellbeing_scores_user_date', 'wellbeing_scores', ['user_id', 'score_date'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_wellbeing_scores_user_date', 'wellbeing_scores', type_='unique')
    # ### end Alembic commands ###
