"""add habit deactivation timestamp

Revision ID: 91561445513d
Revises: 47d3aed7f7bd
Create Date: 2026-10-05 16:37:12.832695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91561445513d'
down_revision: Union[str, Sequence[str], None] = '47d3aed7f7bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('habits', sa.Column('deactivated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('habits', 'deactivated_at')
    # ### end Alembic commands ###
