"""add insight snapshots

Revision ID: d503caa86180
Revises: 91561445513d
Create Date: 2026-10-06 01:23:19.857170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd503caa86180'
down_revision: Union[str, Sequence[str], None] = '91561445513d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('insight_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('insight_key', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('subject', sa.String(length=100), nullable=False),
    sa.Column('direction', sa.String(length=30), nullable=False),
    sa.Column('window_start', sa.Date(), nullable=False),
    sa.Column('window_end', sa.Date(), nullable=False),
    sa.Column('supporting_value', sa.Float(), nullable=True),
    sa.Column('value_bucket', sa.Integer(), nullable=True),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('first_generated_at', sa.DateTime(), nullable=False),
    sa.Column('last_changed_at', sa.DateTime(), nullable=False),
    sa.Column('last_generated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'insight_key', name='uq_insight_snapshot_user_key')
    )
    op.create_index('ix_insight_snapshot_user_last_changed', 'insight_snapshots', ['user_id', 'last_changed_at'], unique=False)
    op.create_index(op.f('ix_insight_snapshots_id'), 'insight_snapshots', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_insight_snapshots_id'), table_name='insight_snapshots')
    op.drop_index('ix_insight_snapshot_user_last_changed', table_name='insight_snapshots')
    op.drop_table('insight_snapshots')
    # ### end Alembic commands ###
